// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4e5vM6bHctOPe-cXET-nbOfKTSVMDOfM',
    appId: '1:787341479203:web:60f836ab23827139ef1096',
    messagingSenderId: '787341479203',
    projectId: 'advmobprog-firebase-52223',
    authDomain: 'advmobprog-firebase-52223.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-52223.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDdujAQwPWqhBtSDLqkrZQFJKjKh94k-A',
    appId: '1:787341479203:android:1b77d2d9c3fb81e6ef1096',
    messagingSenderId: '787341479203',
    projectId: 'advmobprog-firebase-52223',
    storageBucket: 'advmobprog-firebase-52223.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYPdjT7Tt6Zd06HMxb3MSG-b9dcnx6YzA',
    appId: '1:787341479203:ios:4439755038ec8653ef1096',
    messagingSenderId: '787341479203',
    projectId: 'advmobprog-firebase-52223',
    storageBucket: 'advmobprog-firebase-52223.firebasestorage.app',
    iosBundleId: 'com.example.sagunAdvmobprog',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYPdjT7Tt6Zd06HMxb3MSG-b9dcnx6YzA',
    appId: '1:787341479203:ios:4439755038ec8653ef1096',
    messagingSenderId: '787341479203',
    projectId: 'advmobprog-firebase-52223',
    storageBucket: 'advmobprog-firebase-52223.firebasestorage.app',
    iosBundleId: 'com.example.sagunAdvmobprog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4e5vM6bHctOPe-cXET-nbOfKTSVMDOfM',
    appId: '1:787341479203:web:d39f5bb251fc5fc3ef1096',
    messagingSenderId: '787341479203',
    projectId: 'advmobprog-firebase-52223',
    authDomain: 'advmobprog-firebase-52223.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-52223.firebasestorage.app',
  );
}
